package Query

object BenchQueries extends Enumeration {

  // Single table

  val QueryOne =
    """SELECT L_RETURNFLAG, L_LINESTATUS, SUM(L_QUANTITY) AS SUM_QTY, AVG(L_EXTENDEDPRICE) AS AVG_PRICE,
      |AVG(L_DISCOUNT) AS AVG_DISC, COUNT(*) AS COUNT_ORDER,
      |IF (1+ floor ( rand () * 1000) <= 100, 1 + FLOOR(RAND()*100), 0) AS SID
      |FROM LINEITEM
      |GROUP BY L_RETURNFLAG, L_LINESTATUS, SID""".stripMargin.toLowerCase()


  val QueryTwoSid =
    """SELECT L_LINESTATUS, SUM((L_EXTENDEDPRICE*(1-L_DISCOUNT))) AS SUM_REVENUE, O_SHIPPRIORITY,
      |IF (1+ floor ( rand () * 500) <= 50, 1 + FLOOR(RAND()*50), 0) AS O_SID,
      |IF (1+ floor ( rand () * 500) <= 50, 1 + FLOOR(RAND()*50), 0) AS L_SID
      |FROM ORDER JOIN LINEITEM ON ORDER.O_ORDERKEY = LINEITEM.L_ORDERKEY
      |GROUP BY L_LINESTATUS, O_SHIPPRIORITY""".stripMargin.toLowerCase()

  val QueryTwo =
    """SELECT L_LINESTATUS, SUM((L_EXTENDEDPRICE*(1-L_DISCOUNT))) AS SUM_REVENUE, O_SHIPPRIORITY
      |FROM ORDER JOIN LINEITEM ON ORDER.O_ORDERKEY = LINEITEM.L_ORDERKEY
      |GROUP BY L_LINESTATUS, O_SHIPPRIORITY""".stripMargin.toLowerCase()


  // 4 table join
  val QueryThree =
    """SELECT C_MKTSEGMENT, SUM((L_EXTENDEDPRICE*(1-L_DISCOUNT))) AS SUM_REVENUE
      |FROM CUSTOMER JOIN ORDER ON CUSTOMER.C_CUSTKEY = ORDER.O_CUSTKEY
      |JOIN LINEITEM ON LINEITEM.L_ORDERKEY = ORDER.O_ORDERKEY
      |JOIN SUPPLIER ON LINEITEM.L_SUPPKEY = SUPPLIER.S_SUPPKEY
      |GROUP BY C_MKTSEGMENT""".stripMargin.toLowerCase()


  // Single table, no group by
  val QueryFour =
    """SELECT SUM(L_EXTENDEDPRICE*L_DISCOUNT) AS SUM_REVENUE
      |FROM LINEITEM
      |WHERE L_SHIPDATE >= '1994-01-01'
      |AND L_DISCOUNT BETWEEN .06 - 0.01 AND .06 + 0.01 AND L_QUANTITY < 24""".stripMargin.toLowerCase()


  // 3 table join on same key
  val QueryFive =
    """SELECT SUM(L_EXTENDEDPRICE) AS SUM_YEARLY FROM PART
      |JOIN PARTSUPP ON PART.P_PARTKEY = PARTSUPP.PS_PARTKEY
      |JOIN LINEITEM ON PARTSUPP.PS_PARTKEY = LINEITEM.L_PARTKEY
      |WHERE L_QUANTITY < (SELECT 0.2*AVG(L_QUANTITY) FROM LINEITEM WHERE L_PARTKEY = P_PARTKEY)"""
      .stripMargin.toLowerCase()

  // 3 table
  val QuerySix =
    """SELECT SUM((L_EXTENDEDPRICE*(1-L_DISCOUNT))) AS SUM_REVENUE, O_ORDERSTATUS, O_ORDERPRIORITY
      |FROM CUSTOMER JOIN ORDER ON CUSTOMER.C_CUSTKEY = ORDER.O_CUSTKEY
      |JOIN LINEITEM ON LINEITEM.L_ORDERKEY = ORDER.O_ORDERKEY
      |WHERE O_ORDERDATE < '1995-03-15'
      |GROUP BY O_ORDERPRIORITY, O_ORDERSTATUS""".stripMargin.toLowerCase()

  // Rare groups
  val QuerySeven =
    """SELECT SUM((L_EXTENDEDPRICE*(1-L_DISCOUNT))) AS SUM_REVENUE, O_ORDERDATE
      |FROM CUSTOMER JOIN ORDER ON CUSTOMER.C_CUSTKEY = ORDER.O_CUSTKEY
      |JOIN LINEITEM ON LINEITEM.L_ORDERKEY = ORDER.O_ORDERKEY
      |WHERE O_ORDERDATE < '1995-03-15'
      |GROUP BY O_ORDERDATE""".stripMargin.toLowerCase()

  val QueryEight =
    """SELECT (L_EXTENDEDPRICE*(1-L_DISCOUNT)) AS SUM_REVENUE, O_ORDERSTATUS, O_ORDERPRIORITY, O_ORDERDATE
      |FROM CUSTOMER JOIN ORDER ON CUSTOMER.C_CUSTKEY = ORDER.O_CUSTKEY
      |JOIN LINEITEM ON ORDER.O_ORDERKEY = LINEITEM.L_ORDERKEY""".stripMargin.toLowerCase()

  // Rare groups
  val QuerySevenAvg =
    """SELECT AVG((L_EXTENDEDPRICE*(1-L_DISCOUNT))) AS AVG_REVENUE, O_ORDERDATE
      |FROM CUSTOMER JOIN ORDER ON CUSTOMER.C_CUSTKEY = ORDER.O_CUSTKEY
      |JOIN LINEITEM ON ORDER.O_ORDERKEY = LINEITEM.L_ORDERKEY
      |WHERE O_ORDERDATE < '1995-03-15'
      |GROUP BY O_ORDERDATE""".stripMargin.toLowerCase()

  val QuerySixAvg =
    """SELECT AVG((L_EXTENDEDPRICE*(1-L_DISCOUNT))) AS AVG_REVENUE, O_ORDERSTATUS, O_ORDERPRIORITY
      |FROM CUSTOMER JOIN ORDER ON CUSTOMER.C_CUSTKEY = ORDER.O_CUSTKEY
      |JOIN LINEITEM ON LINEITEM.L_ORDERKEY = ORDER.O_ORDERKEY
      |WHERE O_ORDERDATE < '1995-03-15'
      |GROUP BY O_ORDERPRIORITY, O_ORDERSTATUS""".stripMargin.toLowerCase()

  val QueryFiveAvg =
    """SELECT AVG(L_EXTENDEDPRICE) AS AVG_YEARLY FROM PART
      |JOIN PARTSUPP ON PART.P_PARTKEY = PARTSUPP.PS_PARTKEY
      |JOIN LINEITEM ON PARTSUPP.PS_PARTKEY = LINEITEM.L_PARTKEY
      |GROUP BY PART.P_CONTAINER"""
      .stripMargin.toLowerCase()

  val QueryFiveTemp =
    """SELECT L_EXTENDEDPRICE AS AVG_YEARLY, P_CONTAINER FROM PART
      |JOIN PARTSUPP ON PART.P_PARTKEY = PARTSUPP.PS_PARTKEY
      |JOIN LINEITEM ON PARTSUPP.PS_PARTKEY = LINEITEM.L_PARTKEY"""
      .stripMargin.toLowerCase()

}
